### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by dodocommando** [nachos/windowz#2]
I get the same error when trying to run or test it. I'm using node 6.7.0. 

```
[13:59:02] Starting 'test'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
 Error: Could not locate the bindings file. Tried:
 → D:\windowz\build\windows.node
 → D:\windowz\build\Debug\windows.node
 → D:\windowz\build\Release\windows.node
 → D:\windowz\out\Debug\windows.node
 → D:\windowz\Debug\windows.node
 → D:\windowz\out\Release\windows.node
 → D:\windowz\Release\windows.node
 → D:\windowz\build\default\windows.node
 → D:\windowz\compiled\6.3.0\win32\x64\windows.node
    at bindings (D:\windowz\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (D:\windowz\lib\index.js:9:125)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions.(anonymous function) [as .js] (D:\windowz\node_modules\istanbul\lib\hook.js:107:24)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Suite.<anonymous> (D:\windowz\test\main.spec.js:7:17)
 npm ERR! Test failed.  See above for more details.
```

**Comment by noamokman** [comment]
You should ask @omrilitov the maintainer
